version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 453651376318.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile-prod -t hello-world .
      - docker tag hello-world:latest 453651376318.dkr.ecr.us-east-1.amazonaws.com/hello-world:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 453651376318.dkr.ecr.us-east-1.amazonaws.com/hello-world:latest
      - printf '[{"name":"express","imageUri":"%s"}]' 453651376318.dkr.ecr.us-east-1.amazonaws.com/hello-world > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json
